spring:
  application:
    name: display

server:
  port: 8081

#https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
  command:
    default: #HystrinxCommand의 Default Property. HystrixCommand의 Key를 기입하여 Key별 설정(Dynamic Instance Property)이 가능하다.
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # HystrixCommand의 timeout을 caller가 observe 하며 callback을 기다려주는 시간(밀리세컨). 디폴트 1000.
      circuitBreaker:
        requestVolumeThreshold: 1 # 요청크기임계. circuit open 필수조건 2가지중 하나. 디폴트 20. 한 Rolling window(10초)내 들어오는 call 수가 본 설정을 넘어서면 조건만족
        errorThresholdPercentage: 50 # 에러임계비율. circuit open 필수조건 2가지중 하나. 디폴트 20(%). 한 Rolling window에 들어온 call중 에러비율이 본 비율을 넘어서면 조건만족
